### PR TITLE
Does Login

### PR DESCRIPTION
**Pull request by sagarbadu**
'SignUp' creates a new user and the data is stored in firebase. Username and password is required to login and get access to the Dashboard. If the student forgets the password he/she can reset the password by clicking on 'Forgot Password'. The link in sent to the email and the new password can be created by clicking the email.

### CODE REVIEW

**Review by ericgeil223 — APPROVED** [review]
Everything is in the login folder but it does seem to work well. Needs to be merged with the dashboard ect. but looks good.

**Review by logan-giese — APPROVED** [review]
Looks good, but we still need to merge it into the main project so it's not isolated in the "login" project

**Review by n-grounds — APPROVED** [review]
Looks good to me, but as others noted, these changes may get wiped out by the dashboard Pull Request if care isn't taken for that PR

**Comment by n-grounds** [comment]
Is this PR (pull request) still valid, is it going to be merged?  It's from two Sprints ago, now

**Pull request closed without merging**
